export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const GET_FAV_POSTS_REQUEST = "GET_FAV_POSTS_REQUEST";
export const GET_FAV_POSTS_SUCCESS = "GET_FAV_POSTS_SUCCESS";
export const GET_FAV_POSTS_FAILURE = "GET_FAV_POSTS_FAILURE";
